# Site name
site_name: PySNA Documentation

# GitHub
repo_url: https://github.com/mathun3003/PySNA

# Navigation menu
nav:
  - Home: index.md
  - Installation: user-guide/installation.md
  - Quick Start: user-guide/quick-start.md
  - User Guide:
      - TwitterAPI: user-guide/overview/TwitterAPI.md
      - Utility Functions: user-guide/overview/Utilities.md
      - CLI Tool: user-guide/overview/cli.md
  - Implementation Details: # TODO
      - TwitterAPI: maintenance/TwitterAPI.md
      - TwitterDataFetcher: maintenance/TwitterDataFetcher.md
      - TwitterDataProcessor: maintenance/TwitterDataProcessor.md
      - BaseDataProcessor: maintenance/BaseDataProcessor.md
      - Utility Functions: maintenance/utils.md
      - CLI Functions: maintenance/cli.md
      - Software Testing: maintenance/testing.md
      - Repository Information: maintenance/repository.md # TODO

# Theme
theme:
    features:
      - tabs
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
        - bash

# Plugins
plugins:
  - search
